name: ci

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "pom.xml"
  pull_request:
    branches: [main]
permissions:
  packages: write

concurrency:
  group: ci
  cancel-in-progress: false

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout
        uses: actions/checkout@v4
      - name: cache ~/.m2
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: mvn clean compile
        run: $MVN clean compile
      - name: mvn test
        run: $MVN test
